# BEGIN MySQL

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service_name: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    service_name: mysql

# END MySQL

---
# BEGIN MediaWiki

apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki-conf-1
data:
  CustomSettings.php: |
    <?php
    
    /**
     * VisualEditor
     */
    wfLoadExtension( 'VisualEditor' );

    $wgDefaultUserOptions['visualeditor-enable'] = 1;
    $wgHiddenPrefs[] = 'visualeditor-enable';
    $wgVirtualRestConfig['modules']['restbase'] = array(
      'url' => 'http://restbase-svc:7231',
      'domain' => 'localhost',
      'forwardCookies' => true,
      'parsoidCompat' => false
    );

    /**
     * Math
     */
    #wfLoadExtension( 'Math' );
    #$wgMathValidModes[] = 'mathml';
    #$wgDefaultUserOptions['math'] = 'mathml';
    #$wgMathFullRestbaseURL = 'http://restbase-svc:7231/localhost/';
    #unset($GLOBALS['wgMathMathMLUrl']);

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediawiki-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service_name: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: wikimedia/mediawiki:1.30.0-wmf3
          ports:
            - containerPort: 80
          env:
            - name: MEDIAWIKI_SITE_SERVER
              value: //localhost
            - name: MEDIAWIKI_SITE_NAME
              value: MediaWiki
            - name: MEDIAWIKI_SITE_LANG
              value: en
            - name: MEDIAWIKI_ADMIN_USER
              value: admin
            - name: MEDIAWIKI_ADMIN_PASS
              value: admin
            - name: MEDIAWIKI_UPDATE
              value: 'true'
            - name: MEDIAWIKI_DB_TYPE
              value: mysql
            - name: MEDIAWIKI_DB_USER
              value: root
            - name: MEDIAWIKI_DB_PASSWORD
              value: password
            - name: MEDIAWIKI_DB_HOST
              value: mysql-svc
            - name: MEDIAWIKI_RESTBASE_URL
              value: http://restbase-svc:7231/localhost/v1
          volumeMounts:
            - name: mediawiki-storage
              mountPath: /data
            - name: mediawiki-conf
              mountPath: /conf

      volumes:
        - name: mediawiki-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mediawiki
        - name: mediawiki-conf
          configMap:
            name: mediawiki-conf-1

---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service_name: mediawiki

# END MediaWiki
---
# BEGIN RESTBase
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: restbase-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service_name: restbase
    spec:
      containers:
        - name: mediawiki-node-services
          image: wikimedia/mediawiki-node-services:0.2.1
          env:
            - name: MEDIAWIKI_API_URL
              value: http://mediawiki-svc/api.php
          volumeMounts:
            - name: node-services-storage
              mountPath: /data

      volumes:
        - name: node-services-storage
          hostPath:
            path: /var/lib/mediawiki-containers/node-services
---
apiVersion: v1
kind: Service
metadata:
  name: restbase-svc
spec:
  type: ClusterIP
  ports:
  - port: 7231
    protocol: TCP
  selector:
    service_name: restbase

# END RESTBase

---
# BEGIN Mathoid
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mathoid-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service_name: mathoid
    spec:
      containers:
        - name: mathoid
          image: wikimedia/mathoid:24b660f09
          ports:
            - containerPort: 10044
---
apiVersion: v1
kind: Service
metadata:
  name: mathoid-svc
spec:
  type: ClusterIP
  ports:
  - port: 10044
    protocol: TCP
  selector:
    service_name: mathoid

# END Mathoid

