apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediawiki-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service_name: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: wikimedia/mediawiki
          ports:
            - containerPort: 80
          env:
            - name: MEDIAWIKI_SITE_SERVER
              value: //localhost
            - name: MEDIAWIKI_SITE_NAME
              value: MediaWiki
            - name: MEDIAWIKI_SITE_LANG
              value: en
            - name: MEDIAWIKI_ADMIN_USER
              value: admin
            - name: MEDIAWIKI_ADMIN_PASS
              value: admin
            - name: MEDIAWIKI_UPDATE
              value: 'true'
            - name: MEDIAWIKI_DB_USER
              value: root
            - name: MEDIAWIKI_DB_PASSWORD
              value: password
            - name: MEDIAWIKI_DB_HOST
              value: 127.0.0.1
            - name: MEDIAWIKI_RESTBASE_URL
              value: http://localhost:7231/api/rest_v1
          volumeMounts:
            - name: mediawiki-storage
              mountPath: /data
            - name: mediawiki-conf
              mountPath: /conf

        - name: mediawiki-node-services
          image: wikimedia/mediawiki-node-services:0.2.1
          env:
            - name: MEDIAWIKI_API_URL
              value: http://localhost/api.php
          volumeMounts:
            - name: node-services-storage
              mountPath: /data

        - name: mathoid
          image: wikimedia/mathoid:24b660f09
          ports:
            - containerPort: 10044

        - name: mysql
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: node-services-storage
          hostPath:
            path: /var/lib/mediawiki-containers/node-services
        - name: mediawiki-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mediawiki
        - name: mysql-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mysql
        - name: mediawiki-conf
          configMap:
            name: mediawiki-conf-1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki-conf-1
data:
  CustomSettings.php: |
    <?php
    
    /**
     * VisualEditor
     */
    require_once "/usr/src/mediawiki/extensions/VisualEditor/VisualEditor.php";
    $wgDefaultUserOptions['visualeditor-enable'] = 1;
    $wgHiddenPrefs[] = 'visualeditor-enable';
    $wgVirtualRestConfig['modules']['restbase'] = array(
      'url' => 'http://localhost:7231',
      'domain' => 'localhost',
      'forwardCookies' => true,
      'parsoidCompat' => false
    );

    /**
     * Math
     */
    $wgDefaultUserOptions['math'] = 'mathml';
    $wgMathFullRestbaseURL = 'http://localhost:7231/localhost/';
    wfLoadExtension( 'Math' );

---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service_name: mediawiki
